apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cisqua.fullname" . }}
  labels:
    {{- include "cisqua.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cisqua.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cisqua.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- with .Values.podSecurityContext }}
        runAsNonRoot: {{ .runAsNonRoot }}
        runAsUser: {{ .runAsUser }}
        runAsGroup: {{ .runAsGroup }}
        fsGroup: {{ .fsGroup }}
        fsGroupChangePolicy: {{ .fsGroupChangePolicy }}
        {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.network.appPort }}
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: {{ .Values.network.appPort }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path | quote }}
              port: {{ .Values.network.appPort }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.appStorage }}
            - name: app-data
              mountPath: {{ .appDataVolume.mountPath }}
            {{- range $index, $storage := .additionalStorages }}
            - name: "additional-storage-{{ $index }}"
              mountPath: {{ $storage.mountPath }}
              readOnly: {{ $storage.readOnly }}
            {{- end }}
          {{- end }}
          env:
            - name: TZ
              value: {{.Values.general.timezone | quote }}
            - name: RACK_ENV
              value: {{.Values.general.appEnvironment | quote }}
            - name: UMASK
              value: {{ .Values.general.UMASK | quote }}
            {{- range .Values.general.envList }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
      volumes:
        {{- with .Values.appStorage }}
        - name: app-data
          {{- if .appDataHostPath }}
          hostPath:
            path: {{ .appDataHostPath }}
            type: {{ default "Directory" .appDataVolume.hostPath.type }}
          {{- end }}
        {{- range $index, $storage := .additionalStorages }}
        - name: "additional-storage-{{ $index }}"
          hostPath:
            path: {{ $storage.hostPath.path }}
            type: {{ default "Directory" $storage.hostPath.type }}
        {{- end }}
        {{- end }}


