apiVersion: v1
kind: Service
metadata:
  name: {{ include "cisqua.fullname" . }}
  labels:
    {{- include "cisqua.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.network.servicePort }}
      targetPort: {{ .Values.network.appPort }}
      nodePort: {{ .Values.network.webPort }}
      protocol: TCP
  selector:
    {{- include "cisqua.selectorLabels" . | nindent 4 }}
