apiVersion: v2
name: cisqua
description: A Helm chart for Cisqua

type: application

version: 1.0.0

appVersion: "1.16.0"
icon: https://raw.githubusercontent.com/pathsny/cisqua/master/public/favicon.production.ico

