replicaCount: 1

image:
  repository: pathsny/cisqua
  pullPolicy: Always
  tag: latest

general:
  TZ: "Etc/UTC"
  appEnvironment: "production"
  envList: []
  UMASK: "0022"

probes:
  startup:
    failureThreshold: 3
    periodSeconds: 60
  liveness:
    path: "/"
    failureThreshold: 1
    periodSeconds: 60

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
  fsGroupChangePolicy: "OnRootMismatch"

network:
  appPort: 4567
  servicePort: 8080

resources:
  limits: {}
  requests: {}

appStorage:
  appDataHostPath: "" # Path on your host machine
  appDataVolume:
    mountPath: "/usr/src/app/data"
    hostPath:
      type: Directory
  additionalStorages: []

metalLB:
  enabled: false
