apiVersion: v1
kind: Service
metadata:
  name: {{ include "cisqua.fullname" . }}
  labels:
    {{- include "cisqua.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.metalLB.enabled }}
    metallb.universe.tf/allow-shared-ip: "{{ include "cisqua.fullname" . }}"
    {{- end }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.network.servicePort }}
      targetPort: {{ .Values.network.appPort }}
      name: main
      protocol: TCP
  selector:
    {{- include "cisqua.selectorLabels" . | nindent 4 }}
